### ISSUE TITLE
Discuss behaviour of bold fonts

### ISSUE THREAD

**Issue by Pseudomanifold** [Pseudomanifold/latex-mimosis#10]
This should either become an entry for the FAQ, or I should just change the default font. Would also be a nice addition to the documentation.

**Comment by diarodriguezva** [comment]
Hi, thanks for the beautiful template !
The ebgaramond pkg (https://ctan.org/pkg/ebgaramond?lang=en) supports bold font. However, the version in the apt repo `texlive-fonts-extra` has the older version from 2014 without bold support. When installed manually it works like a charm

**Comment by Pseudomanifold** [comment]
Thanks, I was unaware of this! With a recent `texlive` distribution, it works as well. I added an entry to the FAQ about this.

**Comment by Pseudomanifold** [comment]
(by the way: I added you as a contributor; are you okay with this?)

**Comment by diarodriguezva** [comment]
Sure, thanks!
