### ISSUE TITLE
LaTeX Warning: Unused global option(s): [paper=a4,pagesize].

### ISSUE THREAD

**Issue by Sparklester** [Pseudomanifold/latex-mimosis#11]
LaTeX returns this warning when compiling the base template you provided, without having made any changes to it.

Setting the commands it is asking for with `\documentclass[paper=a4,pagesize]{mimosis}` does make the warning go away.

What could be the reason for which this warning is even being displayed? 

I am trying to compile it from Overleaf after cloning this repo into a blank project.

**Comment by Pseudomanifold** [comment]
That's a good point---the options are now obsolete, but they were useful for older versions of the `typearea` package. I have now removed the option; the warning should now be gone. Please let me know if that works!

**Comment by Sparklester** [comment]
No more warnings. Works perfectly.

Thank you!
