### ISSUE TITLE
Use OpenType ordinals

### ISSUE THREAD

**Issue by a-vrma** [Pseudomanifold/latex-mimosis#14]
I noticed you are using ordinals with `\textsuperscript`. I think the special ordinals for Minion Pro look better:

![screenshot-20201028-201600](https://user-images.githubusercontent.com/29077900/97510219-a7ecd800-195a-11eb-8597-2117b8382245.png)

Notice how the top of the ordinal text doesn't go too high in the latter examples. The code I used was

```
Here is the 1\textsuperscript{\textup{st}} and 1{\addfontfeatures{VerticalPosition=Ordinal}st}.
Here is the 2\textsuperscript{\textup{nd}} and 2{\addfontfeatures{VerticalPosition=Ordinal}nd}.
```

Obviously this may or may not work with other fonts and this doesn't work at all with PDFTeX so it might not be the best addition to the template but I just wanted to let you know.

**Comment by Pseudomanifold** [comment]
That's an excellent point; is there a way to always enforce this? Else, I would adjust my own superscript routines for that.

**Comment by a-vrma** [comment]
No. It would be nice if it were possible to detect for OpenType features from using fontspec but I don't think its possible.

**Comment by Pseudomanifold** [comment]
Thanks for the clarification! I added this behaviour now to the template (contingent on people using `fontspec`).
