### ISSUE TITLE
Useful features (MiniToc and header)

### ISSUE THREAD

**Issue by nikosantoniadis** [Pseudomanifold/latex-mimosis#16]
Firstly, I'd like to thank you for your nice template.

As I've spend a lot of time to find these, useful for me, features I'd like to share my findings:

So, to show MiniToc in every chapter, you can use the solution from [here](https://tex.stackexchange.com/questions/517733/using-koma-script-for-defining-toc-for-each-chapter)

Adding a header in pages, excluding the beginning of each chapter, the solution taken from [here](https://tex.stackexchange.com/questions/492933/headsepline-from-koma-script-doesnt-show), the header part in `mimosis.cls` should be changed as:

```
\usepackage[automark,headsepline,plainheadsepline]{scrlayer-scrpage}
\pagestyle{scrheadings}
\automark[section]{chapter}

\lehead*{\headmark}
\cehead{}
\rehead{\headmark}

\lohead{\headmark}
\cohead{}
\rohead*{\headmark}

\newpairofpagestyles[scrheadings]{chapter}{%
	\KOMAoptions{headsepline=false,plainheadsepline=false}%
	\ihead*{}%
	\ohead*{}%
}

\newpairofpagestyles[scrheadings]{part}{%
	\KOMAoptions{headsepline=false,plainheadsepline=false}%
	\ihead*{}%
	\ohead*{}%
}

\renewcommand*\chapterpagestyle{chapter}

\renewcommand*\partpagestyle{part}
```

Maybe you can create an option in your template if anyone would like to use these styles.

**Comment by Pseudomanifold** [comment]
Thanks for this contribution, it's awesome! For now, I'll document it as an extension to the template because I am not sure how easily I can integrate it as a separate option.

**Comment by Pseudomanifold** [comment]
(I added you as a contributor and updated the README accordingly!)
