### ISSUE TITLE
Using in Overleaf

### ISSUE THREAD

**Issue by fc0712** [Pseudomanifold/latex-mimosis#17]
Is it possible to use the template on overleaf?

**Comment by Pseudomanifold** [comment]
Sure; I have not officially exported it there but you can download the repository and upload it there to start a new project. Let me know if that works for you.

**Comment by Pseudomanifold** [comment]
Just started the export; will update this once it's on Overleaf.

**Comment by fc0712** [comment]
Thanks 🙌👍

**Comment by Pseudomanifold** [comment]
The template is on Overleaf now as well: https://www.overleaf.com/latex/templates/latex-mimosis/syptyjpjrzzj. I'll update the README.
