### ISSUE TITLE
Overleaf - Setup (font)

### ISSUE THREAD

**Issue by fc0712** [Pseudomanifold/latex-mimosis#18]
Great job on the template.

Any things I need to consider font wise when using overleaf. Does it support minion pro or do I need  to purchase that font separately?

**Comment by Pseudomanifold** [comment]
Overleaf supports a set of fonts via the `fontspec` mechanism. See [their documentation for some examples](https://www.overleaf.com/learn/latex/Questions/Which_OTF_or_TTF_fonts_are_supported_via_fontspec%3F). Minion Pro is shipped with Adobe Acrobat Reader, so there's no need to purchase anything if you use the template locally.
