### ISSUE TITLE
Glossaries will not show when using 'standalone' package

### ISSUE THREAD

**Issue by bottom-bracket** [Pseudomanifold/latex-mimosis#19]
## Description
In the present configuration, the glossaries and acronyms will not show if one uses the `standalone` package with `mimosis`. I, for instance, use the standalone package to compile external `tikz` figures, it is a handy package if one wants to reuse the figures separately or in other documents with different typesetting options.

However, the `automake` option of the `glossaries` package does not work together with the `standalone` package, so in order to use both, it is necessary to remove the option.

Perhaps it should be removed in the template, with a comment that one can add this option manually, or the other way around, adding a comment saying, that one should remove the option when using `standalone`

I found that this option clash has not been documented somewhere, so I considered it worthy opening an issue for.

## Non working example : 
```
\documentclass{scrbook}
\usepackage[
  acronym,
  automake,
  nogroupskip,
  nopostdot,
  nonumberlist,
  toc,
]{glossaries}
\usepackage{standalone}
\makeglossaries
\newacronym[description={Resolution Bandwidth}]{RBW}{RBW}{resolution bandwidth}
\newglossaryentry{sample}{name={sample},description={an example}}
\begin{document}
\frontmatter
\tableofcontents
\mainmatter%
\chapter{a chapter}
A \gls{sample}.

\glsaddall%
\printglossary[type=\acronymtype]
\printglossary
\end{document}
```
## Working :
```
\documentclass{scrbook}
\usepackage[
  acronym,
  % automake,
  nogroupskip,
  nopostdot,
  nonumberlist,
  toc,
]{glossaries}
\usepackage{standalone}
\makeglossaries
\newacronym[description={Resolution Bandwidth}]{RBW}{RBW}{resolution bandwidth}
\newglossaryentry{sample}{name={sample},description={an example}}
\begin{document}
\frontmatter
\tableofcontents
\mainmatter%
\chapter{a chapter}
A \gls{sample}.

\glsaddall%
\printglossary[type=\acronymtype]
\printglossary
\end{document}
```

**Comment by Pseudomanifold** [comment]
Thanks for raising this issue. To my understanding `automake` is not required anyway if one uses the `latexmkrc` file provided in the project, which makes sure that `makeglossaries` are being called. So I think the easiest solution is indeed to remove the option. I will push a commit—let me know if this works for you!

**Comment by Pseudomanifold** [comment]
Closing this issue for the time being; I acknowledged you as a contributor as well. Please reopen if you find that the fix does not work.

**Comment by bottom-bracket** [comment]
Yes, that works perfectly, thanks! At least for my case this is a proper fix. Indeed I build with latexmk, so no manual call of `makeglossaries` is required. Since most latex editors allow to modify the build commands manually (if one does not use latexmk), this fix should not restrict the usability of the package.
