### ISSUE TITLE
a good "Definition" format/style

### ISSUE THREAD

**Issue by kebairia** [Pseudomanifold/latex-mimosis#28]
As shown in the image, you utilize a really nice **Definition** format out here; 
right now , i'm using your template with **Emacs** and **org-mode**,  could you provide the **latex** code that produces this result?

![definition](https://user-images.githubusercontent.com/3621146/134777749-922c9e09-b9f0-4ac4-9fc4-7e36b96e9ef1.png)

**Comment by Pseudomanifold** [comment]
I defined my own theorem style for definitions:

```latex
\newtheoremstyle{fancy-def}
                {\topsep}
                {\topsep}
                {}
                {}
                {\scshape}
                {.}
                { }
                {}

\theoremstyle{fancy-def}
```

This is the overall style shared for all my definitions, lemmas, and theorems. I also define individual environments like this:

```latex
\newtheorem{defn}{Definition}[chapter]
\newtheorem{lem}[defn]{Lemma}
\newtheorem{thm}[defn]{Theorem}
```

Hope this helps!

**Comment by kebairia** [comment]
Thank you, it worked perfectly.
