### ISSUE TITLE
Broken July 4ᵗʰ ordinal

### ISSUE THREAD

**Issue by mdeff** [Pseudomanifold/latex-mimosis#34]
July 4ᵗʰ isn't correctly typeset (screenshot from the repository's `Latex.pdf`). I believe something redefines `\th`.

![20211103_200045](https://user-images.githubusercontent.com/6806065/140177795-c3344454-3ddd-45d9-925e-62f2aaf15078.png)

Either way, and as an alternative to the FAQ entry, I believe the best option nowadays is to simply input it in Unicode in the source `.tex`. I expect good fonts to be supporting ordinal numbers. I've proposed that solution on the [TeX StackExchange](https://tex.stackexchange.com/a/621236/112999).

**Comment by Pseudomanifold** [comment]
Fixed, thanks a lot! I move the code to `Thesis.tex` so anyone can decide now what to do with it. You are really a power user of that template, Michaël—thanks so much!

**Comment by mdeff** [comment]
Thank you! One might think that I am actively procrastinating on typesetting instead of writing. 🤔
