### ISSUE TITLE
Name of "Gesamtfakultät" changed

### ISSUE THREAD

**Issue by jomazi** [Pseudomanifold/latex-mimosis#40]
Please note that the name of the "Gesamtfakultät" changed (see [Gesamtfakultät für Mathematik, Ingenieur- und Naturwissenschaften](https://www.uni-heidelberg.de/natmath-fakultaet/)). This should be changed in the respective title document, [Title_Dissertation_Heidelberg.tex](https://github.com/Pseudomanifold/latex-mimosis/blob/master/Sources/Title_Dissertation_Heidelberg.tex).

**Comment by Pseudomanifold** [comment]
Fixed, thanks for reporting! (would have also worked as a pull request—always happy to merge those)
