### ISSUE TITLE
Citation font size

### ISSUE THREAD

**Issue by axelvugts** [Pseudomanifold/latex-mimosis#41]
I'm relatively new to LaTeX and I'm therefore not sure if my question is related specifically to this template or to LaTeX in general, but I hope you can point me in the right direction :)

When I cite a source using the `\parencite` command, the inserted reference is rendered in a slightly smaller font than the rest of the document.
How can I get these citations to match the font size of the rest of the document?

**Comment by Pseudomanifold** [comment]
You can find this in `bibliography-mimosis.tex`. I did not like the default font size for citations, so I changed that:

```latex
% Make the font size of citations smaller. Depending on your selected
% font, you might not need this.
\renewcommand*{\citesetup}{%
  \biburlsetup
  \small
}
```

The easiest way to make everything work is if you remove this `\renewcommand` altogether.

Hope that helps!

**Comment by axelvugts** [comment]
Tnanks for your quick response.
That fixed it for me!

And thanks for maintaining this template, it's really great for a LaTeX beginner like myself :)
