### ISSUE TITLE
number 1 style not like the letter I

### ISSUE THREAD

**Issue by rgege** [Pseudomanifold/latex-mimosis#45]
I am having a hard time getting the number 1 in a style similar to the screenshot (all the thesis provided managed to get one). I would be very grateful for a tip!

![numone](https://user-images.githubusercontent.com/118618361/214962133-07fb12e1-34e3-4455-8fe6-40c721e50f20.png)

**Comment by Pseudomanifold** [comment]
The number style depends a lot on the font that is being used. What are your current settings here? If you are using something like Garamond, look for an option like "old-style figures."

**Comment by rgege** [comment]
Thank you I found it! I would also like to thank you for such a great, clean and beautiful thesis template, it's a pleasure to work with it.

**Comment by Pseudomanifold** [comment]
Glad to hear that you like it :-)
