### ISSUE TITLE
Conflict with pdfcomment

### ISSUE THREAD

**Issue by TheoDps** [Pseudomanifold/latex-mimosis#50]
Hi

I tried importing `pdfcomment` to create tooltips for my acronyms, but it conflicts with one of the packages loaded by mimosis. I could reproduce the issue on a fresh clone of latex-mimosis by importing `pdfcomment` anywhere after `hyperref`

```
! LaTeX Error: Command \st already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.98     \newcommand*\st{}
```

I am quite a novice to latex, so I am struggling to get which package is the culprit but the `\st` command is defined in soul.

Environment:
* Mac OS
* lualatex 1.16.0
* pdfcomment 2.4a

**Comment by Pseudomanifold** [comment]
Hi,

This seems to indeed be a side-effect of the `soul` package not behaving well. However, it can be easily addressed in your cases. Check for the following lines in `Thesis.tex` and remove them:

```latex
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Ordinals
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\makeatletter
\@ifundefined{st}{%
  \newcommand{\st}{\textsuperscript{\textup{st}}\xspace}
}{}
\@ifundefined{rd}{%
  \newcommand{\rd}{\textsuperscript{\textup{rd}}\xspace}
}{}
\@ifundefined{nd}{%
  \newcommand{\nd}{\textsuperscript{\textup{nd}}\xspace}
}{}
\makeatother
```

You'll lose the option to easily get ordinals, but the package should then work. (You could also leave the other ordinals defined if you like them, technically, it's sufficient to remove the `\st` definition)

That's only a workaround, but it should get you covered. Good luck, let me know if it works!

**Comment by TheoDps** [comment]
Thank you for the quick reply! I was searching for a conflict with another library and did not see these commands. I can import `pdfcomment` and try to use it now.

**Comment by Pseudomanifold** [comment]
Let me know if this resolves the issue.

**Comment by TheoDps** [comment]
I am still figuring out how to style the acronyms but I don't think it is a `latex-mimosis` problem so I guess it is resolved
