### ISSUE TITLE
Figures

### ISSUE THREAD

**Issue by ikelax** [Pseudomanifold/latex-mimosis#52]
How did you create these figures?

<img width="707" alt="image" src="https://github.com/Pseudomanifold/latex-mimosis/assets/163678144/408c0446-0e91-4b2d-bc4d-d7f4f1c813bc">

<img width="715" alt="image" src="https://github.com/Pseudomanifold/latex-mimosis/assets/163678144/da16140f-e640-4586-aab1-2ad4c1ca8b06">

<img width="721" alt="image" src="https://github.com/Pseudomanifold/latex-mimosis/assets/163678144/7c332fcb-b6b0-4ee5-b2f0-7b1f09b7dd58">

Also, thank you for sharing the template. It helps me a lot.

**Comment by Pseudomanifold** [comment]
TikZ and Inkscape. These are from my original dissertation, though, and not related to `latex-mimosis`.
