### ISSUE TITLE
textbf not working in the basic example

### ISSUE THREAD

**Issue by asanakoy** [Pseudomanifold/latex-mimosis#9]
Hi, 

Thanks for a great template!  

But `\textbf` doesn't produce a bold text when compiled with `pdflatex`. 
I guess it is related to the fact that package `ebgaramond` by design does not include a bold weight ([source ink](https://tex.stackexchange.com/questions/235400/how-to-use-boldface-when-using-the-package-ebgaramond-maths)).  
How did you circumvent this?

**Comment by Pseudomanifold** [comment]
Hi,

I styled things without using bold font, but a simple fix would be to use a different font. Palatino (from the `mathpazo`) package might be interesting. If you are using `xetex` or `lualatex`, you can use `fontspec` to choose *any* font---the template should work nonetheless; I merely wanted to provide a default font that was *not* the standard one.

Let me know if that helps!
